---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'This template will create a jenkins server on AWS'
Parameters:
  InstanceType:
    Description: 'Ec2 Instance Type'
    Type: String
    Default: t2.small
    AllowedValues:
      - t1.micro
      - t2.small
      - t2.medium
      - t2.large
    ConstraintDescription: "must be a valid EC2 instance type"
  sshkey:
    Description: "Name of an existing EC2 Keypair to enable SSH access to the instances"
    Type: AWS::EC2::KeyPair::KeyName
  IPWhiteList:
    Description: 'IP Address to whitelist(your IP address followed by /32'
    MinLength: 9
    MaxLength: 18
    Type: String
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    Default: 0.0.0.0/0
    ConstraintDescription: "must be a valid IP CIDR range of the form x.x.x.x/x."
  EmailAddress:
    Description: "What email address will recieve the jenkins password"
    Type: String
    Default: " "
    ConstraintDescription: "must be a valid email address"
  DNSPrefix:
    Description: "Prefix for jenkins DNS record (prefix.zone)"
    Type: String
    Default: "builds"
  DNSZone:
    Description: "Route53-hosted zone to use for the DNS record (<prefix>.<zone>)"
    Type: String
    Default: "Your-website.com"
  S3Bucket:
    Description: "[Optional] Key prefix to use for Jenkins backups"
    Type: String
    Default: ""
  Subnets:
    Description: "List of VPC subnet IDs for the cluster"
    Type: 'List<AWS::EC2::Subnet::Id>'
  VPCId:
    Description: "VPC associated with the provided subnets"
    Type: 'AWS::EC2::VPC::Id'
  AdminSecurityGroup:
    Description: "Existing security group that should be granted administrative access to Jenkins (e.g., 'sg-123456')"
    Default: "Primary"
    Type: List<AWS::EC2::SecurityGroup::Id>
Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-6869aa05
    us-west-1:
      AMI: ami-7172b611
    us-west-2:
      AMI: ami-31490d51
Resources:
  CloudformationLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 7
      
     